openapi: 3.0.0
info:
  title: API Мобильного приложения
  version: 1.0.0
  description: API Мобильного приложения
paths:
  /signup:
    post:
      summary: 'Создает нового пользователя или ищет существующего пользователя по номеру телефона.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
            examples:
              example1:
                value:
                  phone_number: '1234567890'
      responses:
        '200':
          description: 'Успешный ответ'
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: 'Сгенерированный OTP-код. Присутствует до добавления смс-сервиса'

            examples:
              example1:
                value:
                  message: '123456'

        '422':
          description: 'Ошибка валидации или другие ошибки'
  /login:
    post:
      summary: 'Авторизует пользователя с помощью номера телефона и OTP-кода.'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                phone_number:
                  type: string
                code:
                  type: string
            examples:
              example1:
                value:
                  phone_number: '1234567890'
                  code: '123456'
      responses:
        '200':
          description: 'Успешный ответ'
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: 'Токен доступа'
                  refresh_token:
                    type: string
                    description: 'Токен обновления'
                  new_user:
                    type: boolean
                    description: 'Признак нового пользователя'
            examples:
              example1:
                value:
                  token: 'access_token'
                  refresh_token: 'refresh_token'
                  new_user: true
        '401':
          description: 'Ошибка авторизации'
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
              examples:
                example1:
                  value:
                    error: 'Invalid code'
  /user:
    get:
      summary: Получение данных профиля пользователя
      description: Возвращает информацию о профиле текущего пользователя.
      tags:
        - Профиль пользователя
      responses:
        '200':
          description: Данные профиля успешно получены
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
            examples:
              example1:
                value:
                  user_id: 123
                  first_name: 'John'
                  country: 'USA'
                  city: 'New York'
                  birthday: '1990-01-01'
                  email: 'john@example.com'
                  verified_email: true
    put:
      summary: Обновление данных профиля пользователя
      description: Обновляет информацию о профиле текущего пользователя.
      tags:
        - Профиль пользователя
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserInfoUpdate'
            examples:
              example1:
                value:
                  first_name: 'Jane'
                  country: 'Canada'
                  city: 'Toronto'
                  birthday: '1995-02-15'
                  email: 'jane@example.com'
      responses:
        '200':
          description: Данные профиля успешно обновлены
        '400':
          description: Некорректный запрос
    security:
      - BearerAuth: []

components:
  schemas:
    UserInfo:
      type: object
      properties:
        user_id:
          type: integer
          description: Идентификатор пользователя
        first_name:
          type: string
          description: Имя пользователя
        country:
          type: string
          description: Страна пользователя
        city:
          type: string
          description: Город пользователя
        email:
          type: string
          description: Почта пользователя
        email_verified:
          type: boolean
          description: Почта подтверждена
        birthday:
          type: string
          description: Дата рождения

